model_name: ${actor.model_name}
enable_gradient_checkpointing: ${actor.enable_gradient_checkpointing}
gradient_checkpointing_config:
  recompute_granularity: ${actor.gradient_checkpointing_config.recompute_granularity}
  recompute_method: ${actor.gradient_checkpointing_config.recompute_method}
  recompute_num_layers: ${actor.gradient_checkpointing_config.recompute_num_layers}
pp_size: ${actor.pp_size}
sp_size: ${actor.sp_size}
tp_size: ${actor.tp_size}
ep_size: ${actor.ep_size}
etp_size: ${actor.etp_size}
max_length_per_device: ${actor.max_length_per_device}
optimizer:
  lr: 5e-6
  weight_decay: ${actor.weight_decay}
max_grad_norm: ${actor.max_grad_norm}
scheduler: ${actor.scheduler}
warmup_ratio: ${actor.warmup_ratio}
offload_optimizer: ${actor.offload_optimizer}