model_name: null
tf_config:
  bf16: true
  attention_backend: flash
  recompute_granularity: full
  recompute_method: uniform
  recompute_num_layers: 1
pp_size: 1
cp_size: 1
tp_size: 1
ep_size: 1
etp_size: null
max_length_per_device: null
optimizer:
  lr: 5e-6
  weight_decay: 1e-2
max_grad_norm: 1.0
scheduler: cosine
warmup_ratio: 0.1
offload_optimizer: true