model_name: ${actor.model_name}
tf_config:
  bf16: true
  attention_backend: flash
pp_size: ${actor.pp_size}
cp_size: ${actor.cp_size}
tp_size: ${actor.tp_size}
ep_size: ${actor.ep_size}
etp_size: ${actor.etp_size}
max_inference_length_per_device: ${actor.max_length_per_device}
offload_model: true