model_name: null
enable_gradient_checkpointing: true
gradient_checkpointing_config:
  recompute_granularity: full
  recompute_method: uniform
  recompute_num_layers: 1
pp_size: 1
sp_size: 1
tp_size: 1
ep_size: 1
etp_size: 1
max_length_per_device: null
optimizer:
  lr: 1e-6
  weight_decay: 1e-2
max_grad_norm: 1.0
scheduler: constant
warmup_ratio: 0.1
offload_optimizer: true
